export const credentials = {
  EMAILJS_SERVICE_ID: import.meta.env.VITE_APP_EMAILJS_SERVICE_ID,
  EMAILJS_TEMPLATE_ID: import.meta.env.VITE_APP_EMAILJS_TEMPLATE_ID,
  EMAILJS_PUBLIC_KEY: import.meta.env.VITE_APP_EMAILJS_PUBLIC_KEY,
};
